=== deib-polimi/modaclouds-qos-models/metamodels/monitoringrules/monitoring_rules_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mo="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema" xmlns:mt="http://www.modaclouds.eu/xsd/1.0/metrics_schema" xmlns:af="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema" xmlns:gc="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema" xmlns:ac="http://www.modaclouds.eu/xsd/2.0/actions_schema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema" xmlns:pa="http://www.modaclouds.eu/xsd/1.0/parameter_schema" elementFormDefault="qualified" jaxb:version="2.1">
	<xs:import namespace="http://www.modaclouds.eu/xsd/1.0/metrics_schema" schemaLocation="../commons/metrics_schema.xsd"/>
	<xs:import namespace="http://www.modaclouds.eu/xsd/1.0/parameter_schema" schemaLocation="../commons/parameter_schema.xsd"/>
	<xs:import namespace="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema" schemaLocation="../commons/aggregate_functions_schema.xsd"/>
	<xs:import namespace="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema" schemaLocation="grouping_categories_schema.xsd"/>
	<xs:import namespace="http://www.modaclouds.eu/xsd/2.0/actions_schema" schemaLocation="actions_schema.xsd"/>
	<xs:element name="monitoringRules">
		<xs:annotation>
			<xs:documentation>A list of Monitoring Rules</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="monitoringRule" type="mo:monitoringRule" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="monitoringRules"/>
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="monitoringRule">
		<xs:sequence>
			<xs:element name="monitoredTargets" type="mo:monitoredTargets" minOccurs="0"/>
			<xs:element name="metricAggregation" type="mo:monitoringMetricAggregation" minOccurs="0"/>
			<xs:element name="condition" type="xs:string" minOccurs="0"/>
			<xs:element name="actions" type="mo:actions" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
		<xs:attribute name="relatedQosConstraintId" type="xs:string"/>
		<xs:attribute name="parentMonitoringRuleId" type="xs:IDREF">
			<xs:annotation>
				<xs:appinfo>
					<jaxb:property name="parentMonitoringRule">
						<jaxb:baseType name="MonitoringRule"/>
					</jaxb:property>
				</xs:appinfo>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="metricName" type="mt:metricString"/>
		<xs:attribute name="timeStep" type="xs:positiveInteger" use="optional"/>
		<xs:attribute name="timeWindow" type="xs:positiveInteger" use="optional"/>
		<xs:attribute name="startEnabled" type="xs:boolean"/>
		<xs:attribute name="samplingTime" type="xs:positiveInteger"/>
		<xs:attribute name="samplingProbability" type="mo:probability"/>
	</xs:complexType>
	<xs:simpleType name="probability">
		<xs:restriction base="xs:float">
			<xs:maxInclusive value="1"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="monitoredTargets">
		<xs:sequence>
			<xs:element name="monitoredTarget" type="mo:monitoredTarget" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="monitoredTargets"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="inherited" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="monitoredTarget">
		<xs:attribute name="klass" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="monitoringMetricAggregation">
		<xs:sequence>
			<xs:element name="parameter" type="pa:parameter" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="parameters"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="inherited" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="groupingCategoryName" type="xs:string"/>
		<xs:attribute name="aggregateFunction" type="af:aggFunString"/>
	</xs:complexType>
	<xs:complexType name="actions">
		<xs:sequence>
			<xs:element name="action" type="mo:action" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="actions"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="inherited" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="action">
		<xs:sequence>
			<xs:element name="parameter" type="pa:parameter" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="parameters"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="targetRuleID" type="xs:IDREF" use="optional">
			<xs:annotation>
				<xs:appinfo>
					<jaxb:property name="targetRule">
						<jaxb:baseType name="MonitoringRule"/>
					</jaxb:property>
				</xs:appinfo>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== deib-polimi/modaclouds-qos-models/metamodels/samples/monitoring_rules_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<monitoringRules
	xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema ../monitoringrules/monitoring_rules_schema.xsd">
	<monitoringRule id="mr_1" label="CPU Utilization Rule"
		metricName="cpu_utilization" relatedQosConstraintId="qs_1" timeStep="60"
		timeWindow="60" startEnabled="true" samplingProbability="1"
		samplingTime="5">
		<monitoredTargets>
			<monitoredTarget id="tr_1" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="region"
			aggregateFunction="average" />
		<condition>METRIC &gt;= 0.6</condition>
		<actions>
			<action name="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_2" label="Percentile Monitoring Rule"
		metricName="response_time" relatedQosConstraintId="qs_2" timeStep="60"
		startEnabled="true" timeWindow="60" samplingProbability="1"
		samplingTime="5">
		<monitoredTargets>
			<monitoredTarget id="tr_2" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="cloud_provider"
			aggregateFunction="percentile">
			<parameter>95</parameter>
		</metricAggregation>
		<condition>METRIC &gt;= 1</condition>
		<actions>
			<action name="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_3" label="Gold Percentile Monitoring Rule"
		parentMonitoringRuleId="mr_2" samplingProbability="1" samplingTime="5">
		<monitoredTargets>
			<monitoredTarget id="tr_3" />
		</monitoredTargets>
		<metricAggregation inherited="true" />
		<condition>METRIC &gt;= 0.3</condition>
		<actions inherited="true" />
	</monitoringRule>
	<monitoringRule id="mr_4" label="Unhealthy Cloud"
		timeStep="60" startEnabled="true" timeWindow="300"
		samplingProbability="1" samplingTime="5">
		<monitoredTargets />
		<metricAggregation />
		<condition>maxOccurrence(mr_1,0) &amp;&amp; minOccurrence(mr_3,3)</condition>
		<actions>
			<action name="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_5" label="Frontend average response time"
		metricName="response_time" relatedQosConstraintId="qs_3" startEnabled="true"
		timeStep="60" timeWindow="60" samplingProbability="1" samplingTime="5">
		<monitoredTargets>
			<monitoredTarget id="tr_3" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="cloud_provider"
			aggregateFunction="average" />
		<condition>METRIC &gt;= 300</condition>
		<actions>
			<action name="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_6"
		label="Fine grain frontend average response time"
		parentMonitoringRuleId="mr_5" startEnabled="false"
		samplingProbability="1" samplingTime="5">
		<monitoredTargets inherited="true" />
		<metricAggregation inherited="true"
			groupingCategoryName="method" />
		<condition>parentCondition</condition>
		<actions>
			<action name="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_7" label="Enable fine grain RT"
		timeWindow="300" startEnabled="true" timeStep="60"
		samplingProbability="1" samplingTime="5">
		<condition>minOccurrence(mr_5,5)</condition>
		<actions>
			<action targetRuleID="mr_6" name="enable_monitoring_rule" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_8" label="Disable fine grain RT"
		timeWindow="300" startEnabled="true" timeStep="60"
		samplingProbability="1" samplingTime="5">
		<condition>maxOccurrence(mr_5,0)</condition>
		<actions>
			<action targetRuleID="mr_6" name="disable_monitoring_rule" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr_9" label="ResponseTime"
		metricName="response_time" relatedQosConstraintId="qs_10"
		startEnabled="true" timeStep="60" timeWindow="60" samplingProbability="1"
		samplingTime="10">
		<monitoredTargets>
			<monitoredTarget id="_GdmYEMhsEeKON4DtRoKCMw" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="cloud_provider"
			aggregateFunction="average" />
		<condition>METRIC &gt; 2000</condition>
		<actions>
			<action name="notify_violation" />
			<action name="set_sampling_probability" targetRuleID="mr_8">
				<parameter>1.0</parameter>
			</action>
		</actions>
	</monitoringRule>
</monitoringRules>

=== deib-polimi/modaclouds-qos-models/metamodels/examples/monitoring_rules_SpecWeb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<monitoringRules
	xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema ../monitoringrules/monitoring_rules_schema.xsd">
	<monitoringRule id="mr-61310618-1da0-4c7a-aa1b-14a2a45d8a70"
		label="ResponseTime" metricName="ResponseTime"
		relatedQosConstraintId="c1" startEnabled="true" timeStep="60"
		timeWindow="60" samplingProbability="1" samplingTime="10">
		<monitoredTargets>
			<monitoredTarget klass="_GdmYEMhsEeKON4DtRoKCMw" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="CloudProvider"
			aggregateFunction="Average" />
		<condition>METRIC &gt; 2000.0</condition>
		<actions>
			<action name="OutputMetric">
				<parameter name="name">ResponseTimeAvgViolation</parameter>
			</action>
		</actions>
	</monitoringRule>
	<monitoringRule id="mr-57c0287c-fd59-4d19-8030-625395cd35bf"
		label="ResponseTime" metricName="ResponseTime"
		relatedQosConstraintId="c2" startEnabled="true" timeStep="60"
		timeWindow="60" samplingProbability="1" samplingTime="10">
		<monitoredTargets>
			<monitoredTarget klass="_GdmYEMhsEeKON4DtRoKCMw" />
		</monitoredTargets>
		<metricAggregation groupingCategoryName="CloudProvider"
			aggregateFunction="Percentile">
			<parameter name="thPercentile">95</parameter>
		</metricAggregation>
		<condition>METRIC &gt; 3000.0</condition>
		<actions>
			<action name="OutputMetric">
				<parameter name="name">ResponseTimePercViolation</parameter>
			</action>
		</actions>
	</monitoringRule>
</monitoringRules>

=== deib-polimi/modaclouds-qos-models/metamodels/samples/monitoring_rules_SpecWeb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<monitoringRules
	xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema ../monitoringrules/monitoring_rules_schema.xsd">
	<monitoringRule id="mr-61310618-1da0-4c7a-aa1b-14a2a45d8a70"
		label="ResponseTime" metricName="response_time"
		relatedQosConstraintId="c1" startEnabled="true" timeStep="60"
		timeWindow="60" samplingProbability="1" samplingTime="10">
		<monitoredTargets>
			<monitoredTarget id="_GdmYEMhsEeKON4DtRoKCMw" />
		</monitoredTargets>
		<metricAggregation groupingCategory="provider"
			aggregateFunction="average" />
		<condition>METRIC &gt; 2000</condition>
		<actions>
			<action actionID="notify_violation" />
		</actions>
	</monitoringRule>
	<monitoringRule id="mr-57c0287c-fd59-4d19-8030-625395cd35bf"
		label="ResponseTime" metricName="response_time"
		relatedQosConstraintId="c2" startEnabled="true" timeStep="60"
		timeWindow="60" samplingProbability="1" samplingTime="10">
		<monitoredTargets>
			<monitoredTarget id="_GdmYEMhsEeKON4DtRoKCMw" />
		</monitoredTargets>
		<metricAggregation groupingCategory="provider"
			aggregateFunction="percentile">
			<parameter>95</parameter>
		</metricAggregation>
		<condition>METRIC &gt; 3000</condition>
		<actions>
			<action actionID="notify_violation" />
		</actions>
	</monitoringRule>
</monitoringRules>
